version: "3.4"
services:
  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    ulimits:
      nproc: 262144
      nofile:
        soft: 20000
        hard: 65535