CREATE SCHEMA DW_AERO;
USE DW_AERO;
CREATE TABLE DM_PAIS (
 COD_PAIS VARCHAR(10) NOT NULL,
 PAIS VARCHAR(100) NOT NULL,
COD_PAIS2 VARCHAR(10) NULL ,
COD_CONTINENTE VARCHAR(10) NULL ,
CONTINENTE VARCHAR(100) NULL,
LONGITUD DECIMAL(6,2) NULL,
LATITUD DECIMAL(6,2) NULL,
 PRIMARY KEY (COD_PAIS));

CREATE TABLE DM_AEROPUERTOS (
 ID_AEROPUERTO INT NOT NULL,
 NOMBRE_AEROPUERTO VARCHAR(100) NOT NULL,
 CIUDAD_AEROPUERTO VARCHAR(45) NULL,
 COD_PAIS VARCHAR(3) NULL,
 COD_IATA_FAA VARCHAR(3) NULL,
 COD_ICAO VARCHAR(4) NULL,
 LATITUD DECIMAL(14,2) NULL,
 LONGITUD DECIMAL(14,2) NULL,
 ALTITUD DECIMAL(14,2) NULL,
 ZONA_HORARIA INT NULL,
 DST VARCHAR(1) NULL,
 ZONA_HORARIA_TZ VARCHAR(45) NULL,
 PRIMARY KEY (ID_AEROPUERTO));


CREATE TABLE DM_AEROLINEAS (
 ID_AEROLINEA INT NOT NULL,
 NOMBRE_AEROLINEA VARCHAR(100) NOT NULL,
 ALIAS_AEROLINEA VARCHAR(50) NULL,
 COD_IATA VARCHAR(3) NULL,
 COD_ICAO VARCHAR(10) NULL,
 IDENTIFICACION VARCHAR(100) NULL,
 COD_PAIS VARCHAR(3) NULL,
 SW_ACTIVA VARCHAR(1) NULL,
 PRIMARY KEY (ID_AEROLINEA));