version: '3.4'

services:
  cassandra:
    image: 'bitnami/cassandra:3'
    container_name: cassandra
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - './data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
volumes:
  cassandra_data:
    driver: local
