version: '3.4'
services:
  neo4j:
    image: 'bitnami/neo4j:4'
    container_name: neo4j
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - './data:/bitnami'
    environment:
      - NEO4J_AUTH=none
volumes:
  neo4j_data:
    driver: local
